% MATLAB script to reproduce Figure 2.9 for Exercise 2.7
% This script loads the MSE data and plots it using a logarithmic y-axis.

clear; clc; close all;

% Define the SNR range based on the Python script configuration
SNR = 5:5:40;

% Load the .mat files generated by main.py
% Ensure that all four files have been successfully generated and exist in the current folder
load('MSE_mmse_4QAM.mat');
load('MSE_mmse_4QAM_CP_FREE.mat');
load('MSE_dnn_4QAM.mat');
load('MSE_dnn_4QAM_CP_FREE.mat');

% Create a new figure
figure('Name', 'Channel Estimation MSE Performance', 'Position', [100, 100, 700, 500]);
hold on;
grid on;

% Plot LMMSE results (Blue lines, circular markers)
% Solid line for CP, dashed line for CP-free (inter-symbol interference)
semilogy(SNR, MSE_mmse_4QAM, 'b-o', 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', 'w');
hold on; grid on; 
semilogy(SNR, MSE_mmse_4QAM_CP_FREE, 'b--o', 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', 'b');

% Plot DNN results (Red lines, square markers)
% Solid line for CP, dashed line for CP-free
semilogy(SNR, MSE_dnn_4QAM, 'r-s', 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', 'w');
semilogy(SNR, MSE_dnn_4QAM_CP_FREE, 'r--s', 'LineWidth', 2, 'MarkerSize', 8, 'MarkerFaceColor', 'r');
set(gca, 'YScale', 'log');
% Format the plot to make it look professional and academic
xlabel('SNR (dB)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Mean Square Error (MSE)', 'FontSize', 12, 'FontWeight', 'bold');
title('DNN vs LMMSE', 'FontSize', 14);

% Add a legend reflecting the exercise instructions
legend('LMMSE (with CP)', 'LMMSE (without CP)', 'DNN (with CP)', 'DNN (without CP)', ...
       'Location', 'southwest', 'FontSize', 11);

% Set axis limits for better visualization
xlim([5 40]);
hold off;
